#!/bin/sh

IMG=$(find ~/Nextcloud/Wallpapers -type f | shuf -n1)
swaybg -i "$IMG" -m fill 
OLD_PID=$!
while true; do
    sleep 3600
    IMG=$(find ~/Nextcloud/Wallpapers -type f | shuf -n1)
    swaybg -i "$IMG" -m fill 
    NEXT_PID=$!
    sleep 5
    kill $OLD_PID
    OLD_PID=$NEXT_PID
done
